@TennisScoreboard_HostAddress = http://localhost:5052

GET {{TennisScoreboard_HostAddress}}/new-match/
Accept: application/json

###
GET {{TennisScoreboard_HostAddress}}/match-score?guid=${{9fd78de5-3ae4-492d-8489-ca91cadeb4b5}}
Accept: application/json

###





POST {{TennisScoreboard_HostAddress}}/new-match/
Content-Type: application/x-www-form-urlencoded

playerName1=Misha&playerName2=Igor
###
POST {{TennisScoreboard_HostAddress}}/match-score/1
Accept: aplication/json

###
POST {{TennisScoreboard_HostAddress}}/match-score/5
Accept: aplication/json

###
GET {{TennisScoreboard_HostAddress}}/matches?playerName=Vladislav&page=1
Accept: aplication/json

###
GET {{TennisScoreboard_HostAddress}}/matches
Accept: aplication/json

###

POST {{TennisScoreboard_HostAddress}}/new-match/
Content-Type: application/x-www-form-urlencoded

matchRequest=1
###
POST {{TennisScoreboard_HostAddress}}/new-match/
Content-Type: application/x-www-form-urlencoded

playerName1=qweqqqqqqqqqqqqqqq&playerName2=qwertyqqqqqqqqqqqqqqqqq
###

POST {{TennisScoreboard_HostAddress}}/new-match/
Content-Type: application/x-www-form-urlencoded

playerName1=Vladislav&playerName2=Vlad
###
POST {{TennisScoreboard_HostAddress}}/new-match/
Content-Type: application/json

{
  "a": "1"
}
###
POST {{TennisScoreboard_HostAddress}}/new-match/
Content-Type: application/json

{
  "a": "Czech Koruna"
}
###
POST {{TennisScoreboard_HostAddress}}/new-match
Content-Type: application/json

{
   "a": "QQQ"
}

###
POST {{TennisScoreboard_HostAddress}}/new-match
Content-Type: application/json

"a": "1"


###
POST  {{TennisScoreboard_HostAddress}}/new-match/
Content-Type: application/json

{
   "a": "q"
}

###
